vich_uploader:
    db_driver: orm

    mappings:
        documents_images:
            uri_prefix: /images/documents
            upload_destination: '%kernel.project_dir%/public/images/documents'

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
